using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VSI.EDGEAXConnector.Enums.Enums.TMV
{
    public enum ErpSalesLineExtensionProperties
    {
        TMVCONTRACTVALIDFROM,
        TMVCONTRACTCALCULATEFROM,
        TMVCONTRACTVALIDTO,
        TMVCONTRACTPOSSTERMDATE,
        TMVCONTRACTCANCELDATE,
        TMVCONTRACTPOSSCANCELDATE,
        TMVCONTRACTTERMDATE,
        TMVCONTRACTTERMDATEEFFECTIVE,
        TMVAUTOPROLONGATION,
        TMVPURCHORDERFORMNUM,
        TMVCUSTOMERREF,
        TMVCONTRACTSTATUSLINE,
        TMVEULAVERSION,
        TMVBILLINGPERIOD,
        PACLICENSE,
        TMVORIGINALLINEAMOUNT,
        TMVLINEMODIFIED,
        TMVREVERSEDLINE,
        TMVMIGRATEDSALESLINENUMBER,
        TMVAFFILIATIONRECID,
        TMVOLDSALESLINENUMBER,
        TMVOLDSALESLINEACTION,
        TMVSOURCEID,
        TMVPARENT,
        TMVCOUPONCODE,
        TMVCUSTOMERLINENUM
    }
}
