//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSI.EDGEAXConnector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive_RequestResponse
    {
        public int RequestResponseId { get; set; }
        public int StoreId { get; set; }
        public Nullable<int> DataDirectionId { get; set; }
        public string EcomTransactionId { get; set; }
        public string ApplicationName { get; set; }
        public string MethodName { get; set; }
        public string Description { get; set; }
        public string DataPacket { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string RequestInitiatedIP { get; set; }
        public string OutputPacket { get; set; }
        public Nullable<System.DateTime> OutputSentAt { get; set; }
        public string IdentifierKey { get; set; }
        public string IdentifierValue { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string TotalProcessingDuration { get; set; }
    }
}
