//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSI.EDGEAXConnector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityFileNameParameter
    {
        public int EntityFileNameParametersId { get; set; }
        public int StoreId { get; set; }
        public int EntityId { get; set; }
        public string Prefix { get; set; }
        public long StartingParameter { get; set; }
        public long Parameters { get; set; }
        public string Postfix { get; set; }
    
        public virtual EntityFileNameParameter EntityFileNameParameter1 { get; set; }
        public virtual EntityFileNameParameter EntityFileNameParameter2 { get; set; }
    }
}
