//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSI.EDGEAXConnector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappingTemplate
    {
        public int MappingTemplateId { get; set; }
        public string SourceEntity { get; set; }
        public string Name { get; set; }
        public int MappingTemplateTypeId { get; set; }
        public string XML { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public int StoreId { get; set; }
        public string ReadMode { get; set; }
        public string IngramTemplate { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
