//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSI.EDGEAXConnector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public int PaymentMethodId { get; set; }
        public Nullable<int> ParentPaymentMethodId { get; set; }
        public string ECommerceValue { get; set; }
        public string ErpValue { get; set; }
        public Nullable<bool> HasSubMethod { get; set; }
        public string ErpCode { get; set; }
        public bool IsPrepayment { get; set; }
        public int StoreId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsCreditCard { get; set; }
        public bool UsePaymentConnector { get; set; }
        public string ServiceAccountId { get; set; }
        public Nullable<int> PaymentConnectorId { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
