//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSI.EDGEAXConnector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProduct
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string itemId { get; set; }
        public long ErpKey { get; set; }
    }
}
