//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSI.EDGEAXConnector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleCatalogProductStaging
    {
        public long SingleCatalogProductStagingId { get; set; }
        public string ProductRecId { get; set; }
        public string SKU { get; set; }
        public string StoreViewCode { get; set; }
        public string ProductJson { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
