//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSI.EDGEAXConnector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.ConfigurableObject = new HashSet<ConfigurableObject>();
            this.DeliveryMethod = new HashSet<DeliveryMethod>();
            this.DimensionSet = new HashSet<DimensionSet>();
            this.EmailSubscriber = new HashSet<EmailSubscriber>();
            this.IntegrationKey = new HashSet<IntegrationKey>();
            this.MappingTemplate = new HashSet<MappingTemplate>();
            this.PaymentMethod = new HashSet<PaymentMethod>();
            this.Subscriber = new HashSet<Subscriber>();
            this.WorkFlowTransition = new HashSet<WorkFlowTransition>();
            this.ActionRequest = new HashSet<ActionRequest>();
            this.CountryNames = new HashSet<CountryNames>();
        }
    
        public int StoreId { get; set; }
        public string Name { get; set; }
        public int EcomTypeId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public bool IsActive { get; set; }
        public string StoreKey { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int ERPTypeId { get; set; }
        public Nullable<int> DuplicateOf { get; set; }
        public Nullable<bool> IsSFTPDirTreeCreated { get; set; }
        public string RetailChannelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigurableObject> ConfigurableObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMethod> DeliveryMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimensionSet> DimensionSet { get; set; }
        public virtual EcomType EcomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSubscriber> EmailSubscriber { get; set; }
        public virtual ERPType ERPType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegrationKey> IntegrationKey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MappingTemplate> MappingTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentMethod> PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscriber> Subscriber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkFlowTransition> WorkFlowTransition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionRequest> ActionRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryNames> CountryNames { get; set; }
    }
}
