//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSI.EDGEAXConnector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdPartyMessage
    {
        public long ThirdPartyMessageId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string ThirdPartyId { get; set; }
        public string Content { get; set; }
        public string ThirdPartyStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int TransactionStatus { get; set; }
        public string DestinationStoreKey { get; set; }
        public string Currency { get; set; }
        public string AssetId { get; set; }
        public string OrderType { get; set; }
        public string SalesId { get; set; }
        public byte RetryCount { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public string PacLicense { get; set; }
        public string Description { get; set; }
    }
}
