//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace VSI.CommerceLink.Demandware.PriceBook {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31", IsNullable=false)]
    public partial class pricebooks {
        
        private complexTypePriceBook[] pricebookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pricebook")]
        public complexTypePriceBook[] pricebook {
            get {
                return this.pricebookField;
            }
            set {
                this.pricebookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="complexType.PriceBook", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31")]
    public partial class complexTypePriceBook {
        
        private complexTypeHeader headerField;
        
        private complexTypePriceTable[] pricetablesField;
        
        /// <remarks/>
        public complexTypeHeader header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("price-tables")]
        [System.Xml.Serialization.XmlArrayItemAttribute("price-table", IsNullable=false)]
        public complexTypePriceTable[] pricetables {
            get {
                return this.pricetablesField;
            }
            set {
                this.pricetablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="complexType.Header", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31")]
    [System.Xml.Serialization.XmlRootAttribute("header", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31", IsNullable=false)]
    public partial class complexTypeHeader {
        
        private string currencyField;
        
        private complexTypeLocalizedString[] displaynameField;
        
        private complexTypeLocalizedString[] descriptionField;
        
        private bool onlineflagField;
        
        private bool onlineflagFieldSpecified;
        
        private System.DateTime onlinefromField;
        
        private bool onlinefromFieldSpecified;
        
        private System.DateTime onlinetoField;
        
        private bool onlinetoFieldSpecified;
        
        private string parentField;
        
        private sharedTypeCustomAttribute[] customattributesField;
        
        private string pricebookidField;
        
        private simpleTypeImportMode modeField;
        
        private bool modeFieldSpecified;
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("display-name")]
        public complexTypeLocalizedString[] displayname {
            get {
                return this.displaynameField;
            }
            set {
                this.displaynameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public complexTypeLocalizedString[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("online-flag")]
        public bool onlineflag {
            get {
                return this.onlineflagField;
            }
            set {
                this.onlineflagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onlineflagSpecified {
            get {
                return this.onlineflagFieldSpecified;
            }
            set {
                this.onlineflagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("online-from")]
        public System.DateTime onlinefrom {
            get {
                return this.onlinefromField;
            }
            set {
                this.onlinefromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onlinefromSpecified {
            get {
                return this.onlinefromFieldSpecified;
            }
            set {
                this.onlinefromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("online-to")]
        public System.DateTime onlineto {
            get {
                return this.onlinetoField;
            }
            set {
                this.onlinetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onlinetoSpecified {
            get {
                return this.onlinetoFieldSpecified;
            }
            set {
                this.onlinetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("custom-attributes")]
        [System.Xml.Serialization.XmlArrayItemAttribute("custom-attribute", IsNullable=false)]
        public sharedTypeCustomAttribute[] customattributes {
            get {
                return this.customattributesField;
            }
            set {
                this.customattributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("pricebook-id")]
        public string pricebookid {
            get {
                return this.pricebookidField;
            }
            set {
                this.pricebookidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public simpleTypeImportMode mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="complexType.LocalizedString", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31")]
    public partial class complexTypeLocalizedString {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="complexType.PercentageEntry", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31")]
    public partial class complexTypePercentageEntry {
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="complexType.AmountEntry", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31")]
    public partial class complexTypeAmountEntry {
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sharedType.CustomAttribute", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31")]
    public partial class sharedTypeCustomAttribute {
        
        private string[] valueField;
        
        private string[] textField;
        
        private string attributeidField;
        
        private string langField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("attribute-id")]
        public string attributeid {
            get {
                return this.attributeidField;
            }
            set {
                this.attributeidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="simpleType.ImportMode", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31")]
    public enum simpleTypeImportMode {
        
        /// <remarks/>
        delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="complexType.PriceTable", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31")]
    [System.Xml.Serialization.XmlRootAttribute("price-table", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31", IsNullable=false)]
    public partial class complexTypePriceTable {
        
        private System.DateTime onlinefromField;
        
        private bool onlinefromFieldSpecified;
        
        private System.DateTime onlinetoField;
        
        private bool onlinetoFieldSpecified;
        
        private object[] itemsField;
        
        private string priceinfoField;
        
        private string productidField;
        
        private simpleTypePriceTableImportMode modeField;
        
        private bool modeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("online-from")]
        public System.DateTime onlinefrom {
            get {
                return this.onlinefromField;
            }
            set {
                this.onlinefromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onlinefromSpecified {
            get {
                return this.onlinefromFieldSpecified;
            }
            set {
                this.onlinefromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("online-to")]
        public System.DateTime onlineto {
            get {
                return this.onlinetoField;
            }
            set {
                this.onlinetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onlinetoSpecified {
            get {
                return this.onlinetoFieldSpecified;
            }
            set {
                this.onlinetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("amount", typeof(complexTypeAmountEntry))]
        [System.Xml.Serialization.XmlElementAttribute("percentage", typeof(complexTypePercentageEntry))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("price-info")]
        public string priceinfo {
            get {
                return this.priceinfoField;
            }
            set {
                this.priceinfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("product-id")]
        public string productid {
            get {
                return this.productidField;
            }
            set {
                this.productidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public simpleTypePriceTableImportMode mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="simpleType.PriceTableImportMode", Namespace="http://www.demandware.com/xml/impex/pricebook/2006-10-31")]
    public enum simpleTypePriceTableImportMode {
        
        /// <remarks/>
        delete,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("delete-all")]
        deleteall,
    }
}
