//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSI.EDGEAXConnector.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CLMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CLMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSI.EDGEAXConnector.Common.CLMessages", typeof(CLMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering in method: {0}.
        /// </summary>
        internal static string VSICL10000 {
            get {
                return ResourceManager.GetString("VSICL10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied parameter(s) to method {0}: {1}.
        /// </summary>
        internal static string VSICL10001 {
            get {
                return ResourceManager.GetString("VSICL10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data provided by RS to method{0}: {1}.
        /// </summary>
        internal static string VSICL10002 {
            get {
                return ResourceManager.GetString("VSICL10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to be returned by method {0}: {1}.
        /// </summary>
        internal static string VSICL10003 {
            get {
                return ResourceManager.GetString("VSICL10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting from method {0}.
        /// </summary>
        internal static string VSICL10004 {
            get {
                return ResourceManager.GetString("VSICL10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value in Variable {1} in Method {0} is {2}.
        /// </summary>
        internal static string VSICL10005 {
            get {
                return ResourceManager.GetString("VSICL10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling function {1} from {0}.
        /// </summary>
        internal static string VSICL10006 {
            get {
                return ResourceManager.GetString("VSICL10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} is Master, now going to generate its variants.
        /// </summary>
        internal static string VSICL10201 {
            get {
                return ResourceManager.GetString("VSICL10201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to traverse Custom Attributes which are present in Dimension Set table.
        /// </summary>
        internal static string VSICL10202 {
            get {
                return ResourceManager.GetString("VSICL10202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traversing custom attributes =&gt; Dimension Key {0}.
        /// </summary>
        internal static string VSICL10203 {
            get {
                return ResourceManager.GetString("VSICL10203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traversing custom attributes =&gt; Dimension Values {0}.
        /// </summary>
        internal static string VSICL10204 {
            get {
                return ResourceManager.GetString("VSICL10204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension {0} for Product {1}, cannot have more than one dimensions.
        /// </summary>
        internal static string VSICL10205 {
            get {
                return ResourceManager.GetString("VSICL10205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute {0} is missing on Product {1}.
        /// </summary>
        internal static string VSICL10206 {
            get {
                return ResourceManager.GetString("VSICL10206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related product: {0} for Master Product Id: {1} not found in catalog, either add in catalog or remove from related products.
        /// </summary>
        internal static string VSICL10207 {
            get {
                return ResourceManager.GetString("VSICL10207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related/Child product {0} =&gt; of Parent Product {1} found and ready for xml generation.
        /// </summary>
        internal static string VSICL10208 {
            get {
                return ResourceManager.GetString("VSICL10208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now added its Master Product {0} as well for xml generation.
        /// </summary>
        internal static string VSICL10209 {
            get {
                return ResourceManager.GetString("VSICL10209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched products with IsMasterProduct == false in case of Flat Product HIerarchy.
        /// </summary>
        internal static string VSICL10210 {
            get {
                return ResourceManager.GetString("VSICL10210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price as Trade AgreementPrice: {0} for Product: {1}.
        /// </summary>
        internal static string VSICL10211 {
            get {
                return ResourceManager.GetString("VSICL10211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price as Base Price: {0} for Product: {1}.
        /// </summary>
        internal static string VSICL10212 {
            get {
                return ResourceManager.GetString("VSICL10212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the Discount Amount: {0} for Product: {1}.
        /// </summary>
        internal static string VSICL10213 {
            get {
                return ResourceManager.GetString("VSICL10213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Available Physical Inventory: {0} for Product: {1}.
        /// </summary>
        internal static string VSICL10214 {
            get {
                return ResourceManager.GetString("VSICL10214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get catalog \&quot;{0}\&quot; catalog id = {1} from Retail Server for Channel ID {2}.
        /// </summary>
        internal static string VSICL10215 {
            get {
                return ResourceManager.GetString("VSICL10215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AX Category: {0} have {1} No of Products Setup in that category.
        /// </summary>
        internal static string VSICL10216 {
            get {
                return ResourceManager.GetString("VSICL10216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} has {1} Custom Attributes.
        /// </summary>
        internal static string VSICL10217 {
            get {
                return ResourceManager.GetString("VSICL10217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0},.
        /// </summary>
        internal static string VSICL10218 {
            get {
                return ResourceManager.GetString("VSICL10218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address [{0}] exists in AX but yet not synched in Ecommerce by AX to Ecomm Update job. So skipping integration key generation for it.
        /// </summary>
        internal static string VSICL10301 {
            get {
                return ResourceManager.GetString("VSICL10301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order Json: {0}.
        /// </summary>
        internal static string VSICL10501 {
            get {
                return ResourceManager.GetString("VSICL10501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order Status {0}.
        /// </summary>
        internal static string VSICL10801 {
            get {
                return ResourceManager.GetString("VSICL10801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured in method {0}. Error: {1}.
        /// </summary>
        internal static string VSICL30000 {
            get {
                return ResourceManager.GetString("VSICL30000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs/Products not found.
        /// </summary>
        internal static string VSICL30202 {
            get {
                return ResourceManager.GetString("VSICL30202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ERP Products found.
        /// </summary>
        internal static string VSICL30203 {
            get {
                return ResourceManager.GetString("VSICL30203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured in method {0}. Error: {1}.
        /// </summary>
        internal static string VSICL40000 {
            get {
                return ResourceManager.GetString("VSICL40000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing request object in method {0}.
        /// </summary>
        internal static string VSICL40001 {
            get {
                return ResourceManager.GetString("VSICL40001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter missing in method {0}. Paramter name: {1}.
        /// </summary>
        internal static string VSICL40002 {
            get {
                return ResourceManager.GetString("VSICL40002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter out of context in method {0}. {1}.
        /// </summary>
        internal static string VSICL40003 {
            get {
                return ResourceManager.GetString("VSICL40003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found by method {0}.
        /// </summary>
        internal static string VSICL40004 {
            get {
                return ResourceManager.GetString("VSICL40004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Proxy Exception:.
        /// </summary>
        internal static string VSICL40005 {
            get {
                return ResourceManager.GetString("VSICL40005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in GetIndependentProductPriceDiscount, found 0 Catalog.
        /// </summary>
        internal static string VSICL40202 {
            get {
                return ResourceManager.GetString("VSICL40202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 0 or null Discounts, Exception CRT Discounts.
        /// </summary>
        internal static string VSICL40203 {
            get {
                return ResourceManager.GetString("VSICL40203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 0 or null Inventory, Exception CRT Inventory.
        /// </summary>
        internal static string VSICL40204 {
            get {
                return ResourceManager.GetString("VSICL40204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 0 or null Categories, Exception CRT Products.
        /// </summary>
        internal static string VSICL40206 {
            get {
                return ResourceManager.GetString("VSICL40206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 0 or null Products, Exception CRT Products.
        /// </summary>
        internal static string VSICL40207 {
            get {
                return ResourceManager.GetString("VSICL40207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in GetActiveProductPrice, Found 0 Catalog.
        /// </summary>
        internal static string VSICL40208 {
            get {
                return ResourceManager.GetString("VSICL40208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 0 or null Related Products ,Exception CRT Products.
        /// </summary>
        internal static string VSICL40209 {
            get {
                return ResourceManager.GetString("VSICL40209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer with ECom customerid: {0} is not found. Cannot Sync Sales Order.
        /// </summary>
        internal static string VSICL40301 {
            get {
                return ResourceManager.GetString("VSICL40301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Key generation failed in Create Customer Mode.
        /// </summary>
        internal static string VSICL40302 {
            get {
                return ResourceManager.GetString("VSICL40302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer does not exist while saving address.
        /// </summary>
        internal static string VSICL40303 {
            get {
                return ResourceManager.GetString("VSICL40303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Key generation failed in Update/Create Customer Mode.
        /// </summary>
        internal static string VSICL40304 {
            get {
                return ResourceManager.GetString("VSICL40304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sales order found.
        /// </summary>
        internal static string VSICL40501 {
            get {
                return ResourceManager.GetString("VSICL40501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order TenderLines have not TenderTypeId for some TenderLine.
        /// </summary>
        internal static string VSICL40502 {
            get {
                return ResourceManager.GetString("VSICL40502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found in Integration DB. Sales order cannot be processed.
        /// </summary>
        internal static string VSICL40503 {
            get {
                return ResourceManager.GetString("VSICL40503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in getting Product from Integration DB.
        /// </summary>
        internal static string VSICL40504 {
            get {
                return ResourceManager.GetString("VSICL40504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to found sales order&apos;s products prices (GetIndependentProductPriceDiscount) to calculate periodic discount. Sales order cannot be processed.
        /// </summary>
        internal static string VSICL40505 {
            get {
                return ResourceManager.GetString("VSICL40505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECom delivery address id not found. Sales order cannot be processed.
        /// </summary>
        internal static string VSICL40701 {
            get {
                return ResourceManager.GetString("VSICL40701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel is not in Published or InProgress state.
        /// </summary>
        internal static string VSICL41001 {
            get {
                return ResourceManager.GetString("VSICL41001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Attributes Count returned is &apos;{0}&apos;. Error details &apos;{1}&apos;.
        /// </summary>
        internal static string VSICL41002 {
            get {
                return ResourceManager.GetString("VSICL41002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel does not have any listing attributes. Make sure they are included in AX channel management UI.
        /// </summary>
        internal static string VSICL41003 {
            get {
                return ResourceManager.GetString("VSICL41003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation categories count returned is &apos;{0}&apos;. Error details {1}.
        /// </summary>
        internal static string VSICL41004 {
            get {
                return ResourceManager.GetString("VSICL41004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel does not have any categories..
        /// </summary>
        internal static string VSICL41005 {
            get {
                return ResourceManager.GetString("VSICL41005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Time of the failure: {1}.
        /// </summary>
        internal static string VSICL41006 {
            get {
                return ResourceManager.GetString("VSICL41006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find  ecommerce customer from integration database EcomCustomerId: {0}.
        /// </summary>
        internal static string VSICL41101 {
            get {
                return ResourceManager.GetString("VSICL41101", resourceCulture);
            }
        }
    }
}
