//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSI.EDGEAXConnector.Demandware.PaymentMethod
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.18020.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15")]
    [System.Xml.Serialization.XmlRootAttribute("payment-settings", Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15", IsNullable = false)]
    public partial class paymentsettings
    {

        private PaymentMethod[] paymentmethodField;

        private PaymentCard[] paymentcardField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("payment-method")]
        public PaymentMethod[] paymentmethod
        {
            get
            {
                return this.paymentmethodField;
            }
            set
            {
                this.paymentmethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("payment-card")]
        public PaymentCard[] paymentcard
        {
            get
            {
                return this.paymentcardField;
            }
            set
            {
                this.paymentcardField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15")]
    [System.Xml.Serialization.XmlRootAttribute("payment-method", Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15", IsNullable = false)]
    public partial class PaymentMethod
    {

        private LocalizedString[] nameField;

        private LocalizedString[] descriptionField;

        private string imageField;

        private bool enabledflagField;

        private string processoridField;

        private decimal minpurchaseamountField;

        private bool minpurchaseamountFieldSpecified;

        private decimal maxpurchaseamountField;

        private bool maxpurchaseamountFieldSpecified;

        private Country[] countriesField;

        private string[] currenciesField;

        private CustomerGroup[] customergroupsField;

        private CustomAttribute[] customattributesField;

        private PurchaseAmountRange[] rangesField;

        private string methodidField;

        public PaymentMethod()
        {
            this.enabledflagField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public LocalizedString[] name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public LocalizedString[] description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("enabled-flag")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool enabledflag
        {
            get
            {
                return this.enabledflagField;
            }
            set
            {
                this.enabledflagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("processor-id")]
        public string processorid
        {
            get
            {
                return this.processoridField;
            }
            set
            {
                this.processoridField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("min-purchase-amount")]
        public decimal minpurchaseamount
        {
            get
            {
                return this.minpurchaseamountField;
            }
            set
            {
                this.minpurchaseamountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minpurchaseamountSpecified
        {
            get
            {
                return this.minpurchaseamountFieldSpecified;
            }
            set
            {
                this.minpurchaseamountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("max-purchase-amount")]
        public decimal maxpurchaseamount
        {
            get
            {
                return this.maxpurchaseamountField;
            }
            set
            {
                this.maxpurchaseamountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxpurchaseamountSpecified
        {
            get
            {
                return this.maxpurchaseamountFieldSpecified;
            }
            set
            {
                this.maxpurchaseamountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("country", IsNullable = false)]
        public Country[] countries
        {
            get
            {
                return this.countriesField;
            }
            set
            {
                this.countriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("currency", IsNullable = false)]
        public string[] currencies
        {
            get
            {
                return this.currenciesField;
            }
            set
            {
                this.currenciesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("customer-groups")]
        [System.Xml.Serialization.XmlArrayItemAttribute("customer-group", IsNullable = false)]
        public CustomerGroup[] customergroups
        {
            get
            {
                return this.customergroupsField;
            }
            set
            {
                this.customergroupsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("custom-attributes")]
        [System.Xml.Serialization.XmlArrayItemAttribute("custom-attribute", IsNullable = false)]
        public CustomAttribute[] customattributes
        {
            get
            {
                return this.customattributesField;
            }
            set
            {
                this.customattributesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("range", IsNullable = false)]
        public PurchaseAmountRange[] ranges
        {
            get
            {
                return this.rangesField;
            }
            set
            {
                this.rangesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("method-id")]
        public string methodid
        {
            get
            {
                return this.methodidField;
            }
            set
            {
                this.methodidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15")]
    public partial class LocalizedString
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15")]
    public partial class CardNumberSettings
    {

        private bool enablechecksumverificationField;

        private string[] numberlengthField;

        private string[] numberprefixField;

        public CardNumberSettings()
        {
            this.enablechecksumverificationField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("enable-checksum-verification")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool enablechecksumverification
        {
            get
            {
                return this.enablechecksumverificationField;
            }
            set
            {
                this.enablechecksumverificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("number-length")]
        [System.Xml.Serialization.XmlArrayItemAttribute("length", IsNullable = false)]
        public string[] numberlength
        {
            get
            {
                return this.numberlengthField;
            }
            set
            {
                this.numberlengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("number-prefix")]
        [System.Xml.Serialization.XmlArrayItemAttribute("prefix", IsNullable = false)]
        public string[] numberprefix
        {
            get
            {
                return this.numberprefixField;
            }
            set
            {
                this.numberprefixField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15")]
    public partial class PurchaseAmountRange
    {

        private decimal minpurchaseamountField;

        private bool minpurchaseamountFieldSpecified;

        private decimal maxpurchaseamountField;

        private bool maxpurchaseamountFieldSpecified;

        private string currencyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("min-purchase-amount")]
        public decimal minpurchaseamount
        {
            get
            {
                return this.minpurchaseamountField;
            }
            set
            {
                this.minpurchaseamountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minpurchaseamountSpecified
        {
            get
            {
                return this.minpurchaseamountFieldSpecified;
            }
            set
            {
                this.minpurchaseamountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("max-purchase-amount")]
        public decimal maxpurchaseamount
        {
            get
            {
                return this.maxpurchaseamountField;
            }
            set
            {
                this.maxpurchaseamountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxpurchaseamountSpecified
        {
            get
            {
                return this.maxpurchaseamountFieldSpecified;
            }
            set
            {
                this.maxpurchaseamountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15")]
    public partial class CustomAttribute
    {

        private string[] valueField;

        private string[] textField;

        private string attributeidField;

        private string langField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("attribute-id")]
        public string attributeid
        {
            get
            {
                return this.attributeidField;
            }
            set
            {
                this.attributeidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15")]
    public partial class CustomerGroup
    {

        private string groupidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("group-id")]
        public string groupid
        {
            get
            {
                return this.groupidField;
            }
            set
            {
                this.groupidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15")]
    public partial class Country
    {

        private string countrycodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("country-code")]
        public string countrycode
        {
            get
            {
                return this.countrycodeField;
            }
            set
            {
                this.countrycodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15")]
    [System.Xml.Serialization.XmlRootAttribute("payment-card", Namespace = "http://www.demandware.com/xml/impex/paymentsettings/2009-09-15", IsNullable = false)]
    public partial class PaymentCard
    {

        private LocalizedString[] nameField;

        private LocalizedString[] descriptionField;

        private string imageField;

        private bool enabledflagField;

        private CardNumberSettings cardnumbersettingsField;

        private int securitycodelengthField;

        private bool securitycodelengthFieldSpecified;

        private decimal minpurchaseamountField;

        private bool minpurchaseamountFieldSpecified;

        private decimal maxpurchaseamountField;

        private bool maxpurchaseamountFieldSpecified;

        private Country[] countriesField;

        private string[] currenciesField;

        private CustomerGroup[] customergroupsField;

        private CustomAttribute[] customattributesField;

        private PurchaseAmountRange[] rangesField;

        private string cardtypeField;

        public PaymentCard()
        {
            this.enabledflagField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public LocalizedString[] name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public LocalizedString[] description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("enabled-flag")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool enabledflag
        {
            get
            {
                return this.enabledflagField;
            }
            set
            {
                this.enabledflagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("card-number-settings")]
        public CardNumberSettings cardnumbersettings
        {
            get
            {
                return this.cardnumbersettingsField;
            }
            set
            {
                this.cardnumbersettingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("security-code-length")]
        public int securitycodelength
        {
            get
            {
                return this.securitycodelengthField;
            }
            set
            {
                this.securitycodelengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool securitycodelengthSpecified
        {
            get
            {
                return this.securitycodelengthFieldSpecified;
            }
            set
            {
                this.securitycodelengthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("min-purchase-amount")]
        public decimal minpurchaseamount
        {
            get
            {
                return this.minpurchaseamountField;
            }
            set
            {
                this.minpurchaseamountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minpurchaseamountSpecified
        {
            get
            {
                return this.minpurchaseamountFieldSpecified;
            }
            set
            {
                this.minpurchaseamountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("max-purchase-amount")]
        public decimal maxpurchaseamount
        {
            get
            {
                return this.maxpurchaseamountField;
            }
            set
            {
                this.maxpurchaseamountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxpurchaseamountSpecified
        {
            get
            {
                return this.maxpurchaseamountFieldSpecified;
            }
            set
            {
                this.maxpurchaseamountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("country", IsNullable = false)]
        public Country[] countries
        {
            get
            {
                return this.countriesField;
            }
            set
            {
                this.countriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("currency", IsNullable = false)]
        public string[] currencies
        {
            get
            {
                return this.currenciesField;
            }
            set
            {
                this.currenciesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("customer-groups")]
        [System.Xml.Serialization.XmlArrayItemAttribute("customer-group", IsNullable = false)]
        public CustomerGroup[] customergroups
        {
            get
            {
                return this.customergroupsField;
            }
            set
            {
                this.customergroupsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("custom-attributes")]
        [System.Xml.Serialization.XmlArrayItemAttribute("custom-attribute", IsNullable = false)]
        public CustomAttribute[] customattributes
        {
            get
            {
                return this.customattributesField;
            }
            set
            {
                this.customattributesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("range", IsNullable = false)]
        public PurchaseAmountRange[] ranges
        {
            get
            {
                return this.rangesField;
            }
            set
            {
                this.rangesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("card-type")]
        public string cardtype
        {
            get
            {
                return this.cardtypeField;
            }
            set
            {
                this.cardtypeField = value;
            }
        }
    }
}